spring.application.name=springsqs
server.port=8081
spring.cloud.aws.credentials.access-key=YOUR_AWS_ACCESS_KEY_ID
spring.cloud.aws.credentials.secret-key=YOUR_AWS_SECRET_ACCESS_KEY
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.sqs.endpoint=https://sqs.us-east-1.amazonaws.com/969757057276/user-queue
